/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow_gan/python/contrib_utils.py:48: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow_gan/python/contrib_utils.py:80: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow_gan/python/losses/losses_impl.py:73: The name tf.losses.Reduction is deprecated. Please use tf.compat.v1.losses.Reduction instead.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow_gan/python/train.py:766: The name tf.losses.absolute_difference is deprecated. Please use tf.compat.v1.losses.absolute_difference instead.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow_gan/python/train.py:768: The name tf.losses.softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.softmax_cross_entropy instead.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow_gan/python/train.py:1037: The name tf.train.SessionRunHook is deprecated. Please use tf.estimator.SessionRunHook instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/gin/tf/utils.py:34: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/gin/tf/utils.py:34: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

WARNING:tensorflow:From /home/nupkumar/compare_gan/compare_gan/architectures/abstract_arch.py:71: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

WARNING:tensorflow:From /home/nupkumar/compare_gan/compare_gan/gans/modular_gan.py:72: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/gin/tf/external_configurables.py:32: The name tf.train.exponential_decay is deprecated. Please use tf.compat.v1.train.exponential_decay instead.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/gin/tf/external_configurables.py:33: The name tf.train.inverse_time_decay is deprecated. Please use tf.compat.v1.train.inverse_time_decay instead.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/gin/tf/external_configurables.py:50: The name tf.losses.hinge_loss is deprecated. Please use tf.compat.v1.losses.hinge_loss instead.

WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/gin/tf/external_configurables.py:51: The name tf.losses.huber_loss is deprecated. Please use tf.compat.v1.losses.huber_loss instead.

I0923 21:37:27.306560 139861667854144 main.py:110] Gin config: ['../example_configs/biggan_imagenet128_aet.gin']
Gin bindings: []
I0923 21:37:27.317620 139861667854144 runner_lib.py:317] Running schedule 'continuous_eval' with options: {'use_tpu': False, 'batch_size': 2048, 'gan_class': <class 'compare_gan.gans.modular_gan.ModularGAN_Aux_Task_AET_v2'>, 'architecture': 'resnet_biggan_arch', 'training_steps': 250000, 'lambda': 1, 'consistency_ratio': 10, 'augment_w': 4, 'disc_iters': 2, 'z_dim': 120, 'gen_iters': 1, 'aux_net': 'aux_network_aet_v2'}
WARNING:tensorflow:From /home/nupkumar/compare_gan/compare_gan/gans/utils.py:28: The name tf.gfile.IsDirectory is deprecated. Please use tf.io.gfile.isdir instead.

W0923 21:37:27.317765 139861667854144 deprecation_wrapper.py:119] From /home/nupkumar/compare_gan/compare_gan/gans/utils.py:28: The name tf.gfile.IsDirectory is deprecated. Please use tf.io.gfile.isdir instead.

I0923 21:37:27.693031 139861667854144 datasets.py:103] ImageDatasetV2(name=imagenet_128, tfds_name=imagenet2012, resolution=128, colors=3, num_classes=1000, eval_test_samples=50000, seed=547)
evaluatin %%%%%%%%%%%%%%%%%%%%%%%
WARNING:tensorflow:From /home/nupkumar/compare_gan/compare_gan/gans/modular_gan.py:296: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0923 21:37:27.743810 139861667854144 deprecation_wrapper.py:119] From /home/nupkumar/compare_gan/compare_gan/gans/modular_gan.py:296: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

I0923 21:37:27.816693 139861667854144 modular_gan.py:320] Creating module for model gen with inputs {'z': <tf.Tensor 'z_for_eval:0' shape=(?, 120) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(?,) dtype=int32>} and y=Tensor("one_hot:0", shape=(?, 1000), dtype=float32)
WARNING:tensorflow:From /home/nupkumar/compare_gan/compare_gan/architectures/abstract_arch.py:72: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0923 21:37:27.817451 139861667854144 deprecation_wrapper.py:119] From /home/nupkumar/compare_gan/compare_gan/architectures/abstract_arch.py:72: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

I0923 21:37:27.817716 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(?, 120), y=(?, 1000)
WARNING:tensorflow:From /home/nupkumar/compare_gan/compare_gan/architectures/arch_ops.py:543: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

W0923 21:37:27.817909 139861667854144 deprecation_wrapper.py:119] From /home/nupkumar/compare_gan/compare_gan/architectures/arch_ops.py:543: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

I0923 21:37:27.897982 139861667854144 resnet_biggan.py:262] [Generator] z0=(?, 20), z_per_block=['(?, 20)', '(?, 20)', '(?, 20)', '(?, 20)', '(?, 20)'], y_per_block=['(?, 148)', '(?, 148)', '(?, 148)', '(?, 148)', '(?, 148)']
I0923 21:37:28.447338 139861667854144 resnet_biggan.py:150] [Block] (?, 4, 4, 1536) (z=(?, 20), y=(?, 148)) -> (?, 8, 8, 1536)
I0923 21:37:28.797591 139861667854144 resnet_biggan.py:150] [Block] (?, 8, 8, 1536) (z=(?, 20), y=(?, 148)) -> (?, 16, 16, 768)
I0923 21:37:29.238727 139861667854144 resnet_biggan.py:150] [Block] (?, 16, 16, 768) (z=(?, 20), y=(?, 148)) -> (?, 32, 32, 384)
I0923 21:37:29.592194 139861667854144 resnet_biggan.py:150] [Block] (?, 32, 32, 384) (z=(?, 20), y=(?, 148)) -> (?, 64, 64, 192)
I0923 21:37:29.592445 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (?, 64, 64, 192)
WARNING:tensorflow:From /home/nupkumar/compare_gan/compare_gan/architectures/arch_ops.py:741: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
W0923 21:37:29.657521 139861667854144 deprecation.py:323] From /home/nupkumar/compare_gan/compare_gan/architectures/arch_ops.py:741: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33710341d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33710341d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:29.730067 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33710341d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33710341d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370f734a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370f734a8>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:29.861691 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370f734a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370f734a8>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:30.252933 139861667854144 resnet_biggan.py:150] [Block] (?, 64, 64, 192) (z=(?, 20), y=(?, 148)) -> (?, 128, 128, 96)
I0923 21:37:30.253178 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (?, 128, 128, 96)
I0923 21:37:30.439821 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (?, 128, 128, 3)
WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow/python/training/moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0923 21:37:30.442774 139861667854144 deprecation.py:323] From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow/python/training/moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
I0923 21:37:31.250383 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(?, 120), y=(?, 1000)
I0923 21:37:31.258682 139861667854144 resnet_biggan.py:262] [Generator] z0=(?, 20), z_per_block=['(?, 20)', '(?, 20)', '(?, 20)', '(?, 20)', '(?, 20)'], y_per_block=['(?, 148)', '(?, 148)', '(?, 148)', '(?, 148)', '(?, 148)']
I0923 21:37:31.484963 139861667854144 resnet_biggan.py:150] [Block] (?, 4, 4, 1536) (z=(?, 20), y=(?, 148)) -> (?, 8, 8, 1536)
I0923 21:37:31.739026 139861667854144 resnet_biggan.py:150] [Block] (?, 8, 8, 1536) (z=(?, 20), y=(?, 148)) -> (?, 16, 16, 768)
I0923 21:37:32.053892 139861667854144 resnet_biggan.py:150] [Block] (?, 16, 16, 768) (z=(?, 20), y=(?, 148)) -> (?, 32, 32, 384)
I0923 21:37:32.269780 139861667854144 resnet_biggan.py:150] [Block] (?, 32, 32, 384) (z=(?, 20), y=(?, 148)) -> (?, 64, 64, 192)
I0923 21:37:32.270059 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (?, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8b8b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8b8b00>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:32.352393 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8b8b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8b8b00>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8702e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8702e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:32.415622 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8702e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8702e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:32.719397 139861667854144 resnet_biggan.py:150] [Block] (?, 64, 64, 192) (z=(?, 20), y=(?, 148)) -> (?, 128, 128, 96)
I0923 21:37:32.719700 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (?, 128, 128, 96)
I0923 21:37:32.772646 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (?, 128, 128, 3)
WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow_hub/saved_model_lib.py:112: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
W0923 21:37:32.775393 139861667854144 deprecation.py:323] From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow_hub/saved_model_lib.py:112: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
I0923 21:37:33.239252 139861667854144 modular_gan.py:320] Creating module for model gen with inputs {'z': <tf.Tensor 'z_for_eval:0' shape=(8, 120) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(8,) dtype=int32>} and y=Tensor("one_hot:0", shape=(8, 1000), dtype=float32)
I0923 21:37:33.239652 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(8, 120), y=(8, 1000)
I0923 21:37:33.258504 139861667854144 resnet_biggan.py:262] [Generator] z0=(8, 20), z_per_block=['(8, 20)', '(8, 20)', '(8, 20)', '(8, 20)', '(8, 20)'], y_per_block=['(8, 148)', '(8, 148)', '(8, 148)', '(8, 148)', '(8, 148)']
I0923 21:37:33.678993 139861667854144 resnet_biggan.py:150] [Block] (8, 4, 4, 1536) (z=(8, 20), y=(8, 148)) -> (8, 8, 8, 1536)
I0923 21:37:34.238435 139861667854144 resnet_biggan.py:150] [Block] (8, 8, 8, 1536) (z=(8, 20), y=(8, 148)) -> (8, 16, 16, 768)
I0923 21:37:34.586759 139861667854144 resnet_biggan.py:150] [Block] (8, 16, 16, 768) (z=(8, 20), y=(8, 148)) -> (8, 32, 32, 384)
I0923 21:37:34.949625 139861667854144 resnet_biggan.py:150] [Block] (8, 32, 32, 384) (z=(8, 20), y=(8, 148)) -> (8, 64, 64, 192)
I0923 21:37:34.949889 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (8, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371294048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371294048>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:35.055909 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371294048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371294048>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371006f28>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371006f28>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:35.131158 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371006f28>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371006f28>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:35.616300 139861667854144 resnet_biggan.py:150] [Block] (8, 64, 64, 192) (z=(8, 20), y=(8, 148)) -> (8, 128, 128, 96)
I0923 21:37:35.616579 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (8, 128, 128, 96)
I0923 21:37:35.706359 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (8, 128, 128, 3)
I0923 21:37:36.518528 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(8, 120), y=(8, 1000)
I0923 21:37:36.526684 139861667854144 resnet_biggan.py:262] [Generator] z0=(8, 20), z_per_block=['(8, 20)', '(8, 20)', '(8, 20)', '(8, 20)', '(8, 20)'], y_per_block=['(8, 148)', '(8, 148)', '(8, 148)', '(8, 148)', '(8, 148)']
I0923 21:37:36.847741 139861667854144 resnet_biggan.py:150] [Block] (8, 4, 4, 1536) (z=(8, 20), y=(8, 148)) -> (8, 8, 8, 1536)
I0923 21:37:37.047107 139861667854144 resnet_biggan.py:150] [Block] (8, 8, 8, 1536) (z=(8, 20), y=(8, 148)) -> (8, 16, 16, 768)
I0923 21:37:37.243544 139861667854144 resnet_biggan.py:150] [Block] (8, 16, 16, 768) (z=(8, 20), y=(8, 148)) -> (8, 32, 32, 384)
I0923 21:37:37.442093 139861667854144 resnet_biggan.py:150] [Block] (8, 32, 32, 384) (z=(8, 20), y=(8, 148)) -> (8, 64, 64, 192)
I0923 21:37:37.442381 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (8, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337066f908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337066f908>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:37.515773 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337066f908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337066f908>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370694e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370694e80>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:37.573292 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370694e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370694e80>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:37.799330 139861667854144 resnet_biggan.py:150] [Block] (8, 64, 64, 192) (z=(8, 20), y=(8, 148)) -> (8, 128, 128, 96)
I0923 21:37:37.799621 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (8, 128, 128, 96)
I0923 21:37:37.852090 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (8, 128, 128, 3)
I0923 21:37:38.430263 139861667854144 modular_gan.py:320] Creating module for model gen with inputs {'z': <tf.Tensor 'z_for_eval:0' shape=(16, 120) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(16,) dtype=int32>} and y=Tensor("one_hot:0", shape=(16, 1000), dtype=float32)
I0923 21:37:38.430634 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(16, 120), y=(16, 1000)
I0923 21:37:38.449836 139861667854144 resnet_biggan.py:262] [Generator] z0=(16, 20), z_per_block=['(16, 20)', '(16, 20)', '(16, 20)', '(16, 20)', '(16, 20)'], y_per_block=['(16, 148)', '(16, 148)', '(16, 148)', '(16, 148)', '(16, 148)']
I0923 21:37:38.851475 139861667854144 resnet_biggan.py:150] [Block] (16, 4, 4, 1536) (z=(16, 20), y=(16, 148)) -> (16, 8, 8, 1536)
I0923 21:37:39.216181 139861667854144 resnet_biggan.py:150] [Block] (16, 8, 8, 1536) (z=(16, 20), y=(16, 148)) -> (16, 16, 16, 768)
I0923 21:37:39.579601 139861667854144 resnet_biggan.py:150] [Block] (16, 16, 16, 768) (z=(16, 20), y=(16, 148)) -> (16, 32, 32, 384)
I0923 21:37:39.935752 139861667854144 resnet_biggan.py:150] [Block] (16, 32, 32, 384) (z=(16, 20), y=(16, 148)) -> (16, 64, 64, 192)
I0923 21:37:39.936000 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (16, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336a176470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336a176470>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:40.042417 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336a176470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336a176470>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336a0cb9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336a0cb9b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:40.120175 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336a0cb9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336a0cb9b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:40.739866 139861667854144 resnet_biggan.py:150] [Block] (16, 64, 64, 192) (z=(16, 20), y=(16, 148)) -> (16, 128, 128, 96)
I0923 21:37:40.740145 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (16, 128, 128, 96)
I0923 21:37:40.831158 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (16, 128, 128, 3)
I0923 21:37:41.617575 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(16, 120), y=(16, 1000)
I0923 21:37:41.625890 139861667854144 resnet_biggan.py:262] [Generator] z0=(16, 20), z_per_block=['(16, 20)', '(16, 20)', '(16, 20)', '(16, 20)', '(16, 20)'], y_per_block=['(16, 148)', '(16, 148)', '(16, 148)', '(16, 148)', '(16, 148)']
I0923 21:37:41.951516 139861667854144 resnet_biggan.py:150] [Block] (16, 4, 4, 1536) (z=(16, 20), y=(16, 148)) -> (16, 8, 8, 1536)
I0923 21:37:42.144910 139861667854144 resnet_biggan.py:150] [Block] (16, 8, 8, 1536) (z=(16, 20), y=(16, 148)) -> (16, 16, 16, 768)
I0923 21:37:42.338808 139861667854144 resnet_biggan.py:150] [Block] (16, 16, 16, 768) (z=(16, 20), y=(16, 148)) -> (16, 32, 32, 384)
I0923 21:37:42.533763 139861667854144 resnet_biggan.py:150] [Block] (16, 32, 32, 384) (z=(16, 20), y=(16, 148)) -> (16, 64, 64, 192)
I0923 21:37:42.534021 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (16, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371d6db38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371d6db38>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:42.606128 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371d6db38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371d6db38>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371ce8358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371ce8358>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:42.664903 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371ce8358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371ce8358>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:42.893811 139861667854144 resnet_biggan.py:150] [Block] (16, 64, 64, 192) (z=(16, 20), y=(16, 148)) -> (16, 128, 128, 96)
I0923 21:37:42.894107 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (16, 128, 128, 96)
I0923 21:37:42.945441 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (16, 128, 128, 3)
I0923 21:37:43.416877 139861667854144 modular_gan.py:320] Creating module for model gen with inputs {'z': <tf.Tensor 'z_for_eval:0' shape=(32, 120) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(32,) dtype=int32>} and y=Tensor("one_hot:0", shape=(32, 1000), dtype=float32)
I0923 21:37:43.417305 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(32, 120), y=(32, 1000)
I0923 21:37:43.435805 139861667854144 resnet_biggan.py:262] [Generator] z0=(32, 20), z_per_block=['(32, 20)', '(32, 20)', '(32, 20)', '(32, 20)', '(32, 20)'], y_per_block=['(32, 148)', '(32, 148)', '(32, 148)', '(32, 148)', '(32, 148)']
I0923 21:37:44.045197 139861667854144 resnet_biggan.py:150] [Block] (32, 4, 4, 1536) (z=(32, 20), y=(32, 148)) -> (32, 8, 8, 1536)
I0923 21:37:44.398876 139861667854144 resnet_biggan.py:150] [Block] (32, 8, 8, 1536) (z=(32, 20), y=(32, 148)) -> (32, 16, 16, 768)
I0923 21:37:44.750704 139861667854144 resnet_biggan.py:150] [Block] (32, 16, 16, 768) (z=(32, 20), y=(32, 148)) -> (32, 32, 32, 384)
I0923 21:37:45.193355 139861667854144 resnet_biggan.py:150] [Block] (32, 32, 32, 384) (z=(32, 20), y=(32, 148)) -> (32, 64, 64, 192)
I0923 21:37:45.193626 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (32, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371d972e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371d972e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:45.299176 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371d972e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371d972e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371c4ada0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371c4ada0>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:45.375003 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371c4ada0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371c4ada0>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:45.769692 139861667854144 resnet_biggan.py:150] [Block] (32, 64, 64, 192) (z=(32, 20), y=(32, 148)) -> (32, 128, 128, 96)
I0923 21:37:45.769941 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (32, 128, 128, 96)
I0923 21:37:45.857120 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (32, 128, 128, 3)
I0923 21:37:46.779064 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(32, 120), y=(32, 1000)
I0923 21:37:46.788573 139861667854144 resnet_biggan.py:262] [Generator] z0=(32, 20), z_per_block=['(32, 20)', '(32, 20)', '(32, 20)', '(32, 20)', '(32, 20)'], y_per_block=['(32, 148)', '(32, 148)', '(32, 148)', '(32, 148)', '(32, 148)']
I0923 21:37:47.020443 139861667854144 resnet_biggan.py:150] [Block] (32, 4, 4, 1536) (z=(32, 20), y=(32, 148)) -> (32, 8, 8, 1536)
I0923 21:37:47.224213 139861667854144 resnet_biggan.py:150] [Block] (32, 8, 8, 1536) (z=(32, 20), y=(32, 148)) -> (32, 16, 16, 768)
I0923 21:37:47.427540 139861667854144 resnet_biggan.py:150] [Block] (32, 16, 16, 768) (z=(32, 20), y=(32, 148)) -> (32, 32, 32, 384)
I0923 21:37:47.630505 139861667854144 resnet_biggan.py:150] [Block] (32, 32, 32, 384) (z=(32, 20), y=(32, 148)) -> (32, 64, 64, 192)
I0923 21:37:47.630781 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (32, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b9d0b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b9d0b38>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:47.704837 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b9d0b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b9d0b38>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b98b358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b98b358>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:47.764613 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b98b358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b98b358>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:48.098508 139861667854144 resnet_biggan.py:150] [Block] (32, 64, 64, 192) (z=(32, 20), y=(32, 148)) -> (32, 128, 128, 96)
I0923 21:37:48.098808 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (32, 128, 128, 96)
I0923 21:37:48.146944 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (32, 128, 128, 3)
I0923 21:37:48.626418 139861667854144 modular_gan.py:320] Creating module for model gen with inputs {'z': <tf.Tensor 'z_for_eval:0' shape=(64, 120) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(64,) dtype=int32>} and y=Tensor("one_hot:0", shape=(64, 1000), dtype=float32)
I0923 21:37:48.626809 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(64, 120), y=(64, 1000)
I0923 21:37:48.645692 139861667854144 resnet_biggan.py:262] [Generator] z0=(64, 20), z_per_block=['(64, 20)', '(64, 20)', '(64, 20)', '(64, 20)', '(64, 20)'], y_per_block=['(64, 148)', '(64, 148)', '(64, 148)', '(64, 148)', '(64, 148)']
I0923 21:37:49.054580 139861667854144 resnet_biggan.py:150] [Block] (64, 4, 4, 1536) (z=(64, 20), y=(64, 148)) -> (64, 8, 8, 1536)
I0923 21:37:49.416636 139861667854144 resnet_biggan.py:150] [Block] (64, 8, 8, 1536) (z=(64, 20), y=(64, 148)) -> (64, 16, 16, 768)
I0923 21:37:49.990934 139861667854144 resnet_biggan.py:150] [Block] (64, 16, 16, 768) (z=(64, 20), y=(64, 148)) -> (64, 32, 32, 384)
I0923 21:37:50.346497 139861667854144 resnet_biggan.py:150] [Block] (64, 32, 32, 384) (z=(64, 20), y=(64, 148)) -> (64, 64, 64, 192)
I0923 21:37:50.346753 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (64, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b9822e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b9822e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:50.452370 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b9822e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b9822e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370fdfda0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370fdfda0>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:50.529130 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370fdfda0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370fdfda0>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:50.919838 139861667854144 resnet_biggan.py:150] [Block] (64, 64, 64, 192) (z=(64, 20), y=(64, 148)) -> (64, 128, 128, 96)
I0923 21:37:50.920094 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (64, 128, 128, 96)
I0923 21:37:51.004885 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (64, 128, 128, 3)
I0923 21:37:51.908721 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(64, 120), y=(64, 1000)
I0923 21:37:51.917048 139861667854144 resnet_biggan.py:262] [Generator] z0=(64, 20), z_per_block=['(64, 20)', '(64, 20)', '(64, 20)', '(64, 20)', '(64, 20)'], y_per_block=['(64, 148)', '(64, 148)', '(64, 148)', '(64, 148)', '(64, 148)']
I0923 21:37:52.135779 139861667854144 resnet_biggan.py:150] [Block] (64, 4, 4, 1536) (z=(64, 20), y=(64, 148)) -> (64, 8, 8, 1536)
I0923 21:37:52.331392 139861667854144 resnet_biggan.py:150] [Block] (64, 8, 8, 1536) (z=(64, 20), y=(64, 148)) -> (64, 16, 16, 768)
I0923 21:37:52.529094 139861667854144 resnet_biggan.py:150] [Block] (64, 16, 16, 768) (z=(64, 20), y=(64, 148)) -> (64, 32, 32, 384)
I0923 21:37:52.843811 139861667854144 resnet_biggan.py:150] [Block] (64, 32, 32, 384) (z=(64, 20), y=(64, 148)) -> (64, 64, 64, 192)
I0923 21:37:52.844088 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (64, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33719edb38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33719edb38>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:52.917480 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33719edb38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33719edb38>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33718e8358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33718e8358>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:52.977253 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33718e8358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33718e8358>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:53.211420 139861667854144 resnet_biggan.py:150] [Block] (64, 64, 64, 192) (z=(64, 20), y=(64, 148)) -> (64, 128, 128, 96)
I0923 21:37:53.211688 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (64, 128, 128, 96)
I0923 21:37:53.259670 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (64, 128, 128, 3)
I0923 21:37:53.746585 139861667854144 modular_gan.py:320] Creating module for model gen with inputs {'z': <tf.Tensor 'z_for_eval:0' shape=(?, 120) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(?,) dtype=int32>} and y=Tensor("one_hot:0", shape=(?, 1000), dtype=float32)
I0923 21:37:53.747004 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(?, 120), y=(?, 1000)
I0923 21:37:53.766570 139861667854144 resnet_biggan.py:262] [Generator] z0=(?, 20), z_per_block=['(?, 20)', '(?, 20)', '(?, 20)', '(?, 20)', '(?, 20)'], y_per_block=['(?, 148)', '(?, 148)', '(?, 148)', '(?, 148)', '(?, 148)']
I0923 21:37:54.179091 139861667854144 resnet_biggan.py:150] [Block] (?, 4, 4, 1536) (z=(?, 20), y=(?, 148)) -> (?, 8, 8, 1536)
I0923 21:37:54.537776 139861667854144 resnet_biggan.py:150] [Block] (?, 8, 8, 1536) (z=(?, 20), y=(?, 148)) -> (?, 16, 16, 768)
I0923 21:37:55.117827 139861667854144 resnet_biggan.py:150] [Block] (?, 16, 16, 768) (z=(?, 20), y=(?, 148)) -> (?, 32, 32, 384)
I0923 21:37:55.469794 139861667854144 resnet_biggan.py:150] [Block] (?, 32, 32, 384) (z=(?, 20), y=(?, 148)) -> (?, 64, 64, 192)
I0923 21:37:55.470052 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (?, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b620cf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b620cf8>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:55.574242 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b620cf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b620cf8>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33712627f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33712627f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:55.650418 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33712627f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33712627f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:56.134032 139861667854144 resnet_biggan.py:150] [Block] (?, 64, 64, 192) (z=(?, 20), y=(?, 148)) -> (?, 128, 128, 96)
I0923 21:37:56.134296 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (?, 128, 128, 96)
I0923 21:37:56.222521 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (?, 128, 128, 3)
I0923 21:37:57.006314 139861667854144 resnet_biggan.py:236] [Generator] inputs are z=(?, 120), y=(?, 1000)
I0923 21:37:57.014518 139861667854144 resnet_biggan.py:262] [Generator] z0=(?, 20), z_per_block=['(?, 20)', '(?, 20)', '(?, 20)', '(?, 20)', '(?, 20)'], y_per_block=['(?, 148)', '(?, 148)', '(?, 148)', '(?, 148)', '(?, 148)']
I0923 21:37:57.235419 139861667854144 resnet_biggan.py:150] [Block] (?, 4, 4, 1536) (z=(?, 20), y=(?, 148)) -> (?, 8, 8, 1536)
I0923 21:37:57.542463 139861667854144 resnet_biggan.py:150] [Block] (?, 8, 8, 1536) (z=(?, 20), y=(?, 148)) -> (?, 16, 16, 768)
I0923 21:37:57.743260 139861667854144 resnet_biggan.py:150] [Block] (?, 16, 16, 768) (z=(?, 20), y=(?, 148)) -> (?, 32, 32, 384)
I0923 21:37:57.945683 139861667854144 resnet_biggan.py:150] [Block] (?, 32, 32, 384) (z=(?, 20), y=(?, 148)) -> (?, 64, 64, 192)
I0923 21:37:57.945966 139861667854144 resnet_biggan.py:289] [Generator] Applying non-local block to (?, 64, 64, 192)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370af3b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370af3b00>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:58.020547 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370af3b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370af3b00>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370aac4e0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370aac4e0>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:58.080868 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370aac4e0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370aac4e0>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:58.311749 139861667854144 resnet_biggan.py:150] [Block] (?, 64, 64, 192) (z=(?, 20), y=(?, 148)) -> (?, 128, 128, 96)
I0923 21:37:58.312032 139861667854144 resnet_biggan.py:294] [Generator] before final processing: (?, 128, 128, 96)
I0923 21:37:58.363142 139861667854144 resnet_biggan.py:300] [Generator] after final processing: (?, 128, 128, 3)
I0923 21:37:58.881452 139861667854144 modular_gan.py:320] Creating module for model disc with inputs {'images': <tf.Tensor 'images_for_eval:0' shape=(8, 128, 128, 3) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(8,) dtype=int32>} and y=Tensor("one_hot:0", shape=(8, 1000), dtype=float32)
I0923 21:37:58.882247 139861667854144 resnet_biggan.py:379] [Discriminator] inputs are x=(8, 128, 128, 3), y=(8, 1000)
I0923 21:37:59.027120 139861667854144 resnet_biggan.py:150] [Block] (8, 128, 128, 3) (z=None, y=(8, 1000)) -> (8, 64, 64, 96)
I0923 21:37:59.027342 139861667854144 resnet_biggan.py:398] [Discriminator] Applying non-local block to (8, 64, 64, 96)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b16c9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b16c9b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:59.131561 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b16c9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b16c9b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b0d7470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b0d7470>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:37:59.206260 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b0d7470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b0d7470>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:37:59.589398 139861667854144 resnet_biggan.py:150] [Block] (8, 64, 64, 96) (z=None, y=(8, 1000)) -> (8, 32, 32, 192)
I0923 21:37:59.711598 139861667854144 resnet_biggan.py:150] [Block] (8, 32, 32, 192) (z=None, y=(8, 1000)) -> (8, 16, 16, 384)
I0923 21:37:59.832750 139861667854144 resnet_biggan.py:150] [Block] (8, 16, 16, 384) (z=None, y=(8, 1000)) -> (8, 8, 8, 768)
I0923 21:37:59.951086 139861667854144 resnet_biggan.py:150] [Block] (8, 8, 8, 768) (z=None, y=(8, 1000)) -> (8, 4, 4, 1536)
I0923 21:38:00.025614 139861667854144 resnet_biggan.py:150] [Block] (8, 4, 4, 1536) (z=None, y=(8, 1000)) -> (8, 4, 4, 1536)
I0923 21:38:00.025838 139861667854144 resnet_biggan.py:403] [Discriminator] before final processing: (8, 4, 4, 1536)
I0923 21:38:00.063228 139861667854144 resnet_biggan.py:407] [Discriminator] after final processing: (8, 4, 4, 1536)
WARNING:tensorflow:From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1288: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0923 21:38:00.063681 139861667854144 deprecation.py:506] From /home/nupkumar/venv_gan/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1288: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
I0923 21:38:00.093218 139861667854144 resnet_biggan.py:422] [Discriminator] embedded_y for projection: (8, 1536)
I0923 21:38:00.223208 139861667854144 modular_gan.py:320] Creating module for model disc with inputs {'images': <tf.Tensor 'images_for_eval:0' shape=(16, 128, 128, 3) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(16,) dtype=int32>} and y=Tensor("one_hot:0", shape=(16, 1000), dtype=float32)
I0923 21:38:00.223591 139861667854144 resnet_biggan.py:379] [Discriminator] inputs are x=(16, 128, 128, 3), y=(16, 1000)
I0923 21:38:00.344980 139861667854144 resnet_biggan.py:150] [Block] (16, 128, 128, 3) (z=None, y=(16, 1000)) -> (16, 64, 64, 96)
I0923 21:38:00.345209 139861667854144 resnet_biggan.py:398] [Discriminator] Applying non-local block to (16, 64, 64, 96)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337158f390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337158f390>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:38:00.446792 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337158f390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337158f390>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33713e37f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33713e37f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:38:00.523936 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33713e37f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33713e37f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:38:00.689362 139861667854144 resnet_biggan.py:150] [Block] (16, 64, 64, 96) (z=None, y=(16, 1000)) -> (16, 32, 32, 192)
I0923 21:38:00.805609 139861667854144 resnet_biggan.py:150] [Block] (16, 32, 32, 192) (z=None, y=(16, 1000)) -> (16, 16, 16, 384)
I0923 21:38:01.038386 139861667854144 resnet_biggan.py:150] [Block] (16, 16, 16, 384) (z=None, y=(16, 1000)) -> (16, 8, 8, 768)
I0923 21:38:01.156414 139861667854144 resnet_biggan.py:150] [Block] (16, 8, 8, 768) (z=None, y=(16, 1000)) -> (16, 4, 4, 1536)
I0923 21:38:01.231483 139861667854144 resnet_biggan.py:150] [Block] (16, 4, 4, 1536) (z=None, y=(16, 1000)) -> (16, 4, 4, 1536)
I0923 21:38:01.231710 139861667854144 resnet_biggan.py:403] [Discriminator] before final processing: (16, 4, 4, 1536)
I0923 21:38:01.268596 139861667854144 resnet_biggan.py:407] [Discriminator] after final processing: (16, 4, 4, 1536)
I0923 21:38:01.297133 139861667854144 resnet_biggan.py:422] [Discriminator] embedded_y for projection: (16, 1536)
I0923 21:38:01.425139 139861667854144 modular_gan.py:320] Creating module for model disc with inputs {'images': <tf.Tensor 'images_for_eval:0' shape=(32, 128, 128, 3) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(32,) dtype=int32>} and y=Tensor("one_hot:0", shape=(32, 1000), dtype=float32)
I0923 21:38:01.425538 139861667854144 resnet_biggan.py:379] [Discriminator] inputs are x=(32, 128, 128, 3), y=(32, 1000)
I0923 21:38:01.543524 139861667854144 resnet_biggan.py:150] [Block] (32, 128, 128, 3) (z=None, y=(32, 1000)) -> (32, 64, 64, 96)
I0923 21:38:01.543756 139861667854144 resnet_biggan.py:398] [Discriminator] Applying non-local block to (32, 64, 64, 96)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8cf438>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8cf438>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:38:01.643577 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8cf438>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b8cf438>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337111a828>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337111a828>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:38:01.715085 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337111a828>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f337111a828>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:38:01.875315 139861667854144 resnet_biggan.py:150] [Block] (32, 64, 64, 96) (z=None, y=(32, 1000)) -> (32, 32, 32, 192)
I0923 21:38:01.994079 139861667854144 resnet_biggan.py:150] [Block] (32, 32, 32, 192) (z=None, y=(32, 1000)) -> (32, 16, 16, 384)
I0923 21:38:02.111829 139861667854144 resnet_biggan.py:150] [Block] (32, 16, 16, 384) (z=None, y=(32, 1000)) -> (32, 8, 8, 768)
I0923 21:38:02.350067 139861667854144 resnet_biggan.py:150] [Block] (32, 8, 8, 768) (z=None, y=(32, 1000)) -> (32, 4, 4, 1536)
I0923 21:38:02.428277 139861667854144 resnet_biggan.py:150] [Block] (32, 4, 4, 1536) (z=None, y=(32, 1000)) -> (32, 4, 4, 1536)
I0923 21:38:02.428524 139861667854144 resnet_biggan.py:403] [Discriminator] before final processing: (32, 4, 4, 1536)
I0923 21:38:02.468479 139861667854144 resnet_biggan.py:407] [Discriminator] after final processing: (32, 4, 4, 1536)
I0923 21:38:02.499457 139861667854144 resnet_biggan.py:422] [Discriminator] embedded_y for projection: (32, 1536)
I0923 21:38:02.637162 139861667854144 modular_gan.py:320] Creating module for model disc with inputs {'images': <tf.Tensor 'images_for_eval:0' shape=(64, 128, 128, 3) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(64,) dtype=int32>} and y=Tensor("one_hot:0", shape=(64, 1000), dtype=float32)
I0923 21:38:02.637590 139861667854144 resnet_biggan.py:379] [Discriminator] inputs are x=(64, 128, 128, 3), y=(64, 1000)
I0923 21:38:02.760161 139861667854144 resnet_biggan.py:150] [Block] (64, 128, 128, 3) (z=None, y=(64, 1000)) -> (64, 64, 64, 96)
I0923 21:38:02.760401 139861667854144 resnet_biggan.py:398] [Discriminator] Applying non-local block to (64, 64, 64, 96)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b41a390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b41a390>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:38:02.865407 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b41a390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f336b41a390>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370fc9828>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370fc9828>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:38:02.942965 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370fc9828>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3370fc9828>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:38:03.105550 139861667854144 resnet_biggan.py:150] [Block] (64, 64, 64, 96) (z=None, y=(64, 1000)) -> (64, 32, 32, 192)
I0923 21:38:03.222516 139861667854144 resnet_biggan.py:150] [Block] (64, 32, 32, 192) (z=None, y=(64, 1000)) -> (64, 16, 16, 384)
I0923 21:38:03.337942 139861667854144 resnet_biggan.py:150] [Block] (64, 16, 16, 384) (z=None, y=(64, 1000)) -> (64, 8, 8, 768)
I0923 21:38:03.454087 139861667854144 resnet_biggan.py:150] [Block] (64, 8, 8, 768) (z=None, y=(64, 1000)) -> (64, 4, 4, 1536)
I0923 21:38:03.641865 139861667854144 resnet_biggan.py:150] [Block] (64, 4, 4, 1536) (z=None, y=(64, 1000)) -> (64, 4, 4, 1536)
I0923 21:38:03.642105 139861667854144 resnet_biggan.py:403] [Discriminator] before final processing: (64, 4, 4, 1536)
I0923 21:38:03.680848 139861667854144 resnet_biggan.py:407] [Discriminator] after final processing: (64, 4, 4, 1536)
I0923 21:38:03.712004 139861667854144 resnet_biggan.py:422] [Discriminator] embedded_y for projection: (64, 1536)
I0923 21:38:03.845294 139861667854144 modular_gan.py:320] Creating module for model disc with inputs {'images': <tf.Tensor 'images_for_eval:0' shape=(?, 128, 128, 3) dtype=float32>, 'labels': <tf.Tensor 'labels_for_eval:0' shape=(?,) dtype=int32>} and y=Tensor("one_hot:0", shape=(?, 1000), dtype=float32)
I0923 21:38:03.845699 139861667854144 resnet_biggan.py:379] [Discriminator] inputs are x=(?, 128, 128, 3), y=(?, 1000)
I0923 21:38:03.967697 139861667854144 resnet_biggan.py:150] [Block] (?, 128, 128, 3) (z=None, y=(?, 1000)) -> (?, 64, 64, 96)
I0923 21:38:03.967925 139861667854144 resnet_biggan.py:398] [Discriminator] Applying non-local block to (?, 64, 64, 96)
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33714d46d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33714d46d8>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:38:04.068593 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33714d46d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f33714d46d8>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371c8e668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371c8e668>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0923 21:38:04.139559 139861667854144 ag_logging.py:145] Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371c8e668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f3371c8e668>>: AssertionError: Bad argument number for Name: 3, expecting 4
I0923 21:38:04.301428 139861667854144 resnet_biggan.py:150] [Block] (?, 64, 64, 96) (z=None, y=(?, 1000)) -> (?, 32, 32, 192)
I0923 21:38:04.418816 139861667854144 resnet_biggan.py:150] [Block] (?, 32, 32, 192) (z=None, y=(?, 1000)) -> (?, 16, 16, 384)
I0923 21:38:04.536354 139861667854144 resnet_biggan.py:150] [Block] (?, 16, 16, 384) (z=None, y=(?, 1000)) -> (?, 8, 8, 768)
I0923 21:38:04.652829 139861667854144 resnet_biggan.py:150] [Block] (?, 8, 8, 768) (z=None, y=(?, 1000)) -> (?, 4, 4, 1536)
I0923 21:38:04.726766 139861667854144 resnet_biggan.py:150] [Block] (?, 4, 4, 1536) (z=None, y=(?, 1000)) -> (?, 4, 4, 1536)
I0923 21:38:04.726988 139861667854144 resnet_biggan.py:403] [Discriminator] before final processing: (?, 4, 4, 1536)
I0923 21:38:04.764572 139861667854144 resnet_biggan.py:407] [Discriminator] after final processing: (?, 4, 4, 1536)
I0923 21:38:04.793320 139861667854144 resnet_biggan.py:422] [Discriminator] embedded_y for projection: (?, 1536)
I0923 21:38:05.027085 139861667854144 runner_lib.py:265] eval_tasks: [<compare_gan.metrics.inception_score.InceptionScoreTask object at 0x7f3372ecdda0>, <compare_gan.metrics.fid_score.FIDScoreTask object at 0x7f3372e6e940>]
I0923 21:38:05.027291 139861667854144 runner_lib.py:157] Looking for checkpoints in gs://fewshot_gan/model_imagenet_aet_bce0.5
I0923 21:38:06.287128 139861667854144 runner_lib.py:177] Found checkpoints: {'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-0', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-30000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-5000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-10000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-60000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-45000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-15000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-75000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-25000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-65000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-40000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-50000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-55000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-35000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-70000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-20000'}
Evaluated checkpoints: set()
Unevaluated checkpoints: []
I0923 21:39:06.865248 139861667854144 runner_lib.py:177] Found checkpoints: {'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-0', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-30000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-5000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-10000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-60000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-45000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-15000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-75000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-25000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-65000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-40000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-50000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-55000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-35000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-70000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-20000'}
Evaluated checkpoints: set()
Unevaluated checkpoints: []
I0923 21:40:07.508789 139861667854144 runner_lib.py:177] Found checkpoints: {'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-0', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-30000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-5000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-10000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-60000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-45000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-15000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-75000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-25000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-65000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-40000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-50000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-55000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-35000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-70000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-20000'}
Evaluated checkpoints: set()
Unevaluated checkpoints: []
I0923 21:41:08.101461 139861667854144 runner_lib.py:177] Found checkpoints: {'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-0', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-30000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-5000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-10000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-60000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-45000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-15000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-75000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-25000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-65000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-40000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-50000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-55000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-35000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-70000', 'gs://fewshot_gan/model_imagenet_aet_bce0.5/model.ckpt-20000'}
Evaluated checkpoints: set()
Unevaluated checkpoints: []
